name = "StabilityRegions"
uuid = "0c5038d4-0060-453e-b78d-f4c0ea87ea0f"
authors = ["mforets <mforets@gmail.com>"]
version = "0.1.0"

[deps]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.3, 1.4"
LazySets = "1.34"
MathematicalSystems = "0.11"
Parameters = "0.12"
ReachabilityAnalysis = "0.2"
Reexport = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
